# Generated by Django 5.0.6 on 2024-05-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiszki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polish_word', models.CharField(max_length=100)),
                ('english_word', models.CharField(max_length=100)),
                ('correct_guesses', models.IntegerField(default=0)),
                ('last_correct_guess', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
