# Generated by Django 5.0.6 on 2024-05-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiszki', '0002_fiszki_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiszki',
            name='last_correct_guess',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
